# Generated by Django 4.2.6 on 2023-11-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_employee_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
