# Generated by Django 4.2.6 on 2023-11-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_emp_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=20)),
                ('publication_year', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
    ]
