# Generated by Django 4.2.6 on 2023-12-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_mobilmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('course', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=20)),
            ],
        ),
    ]
